source 'https://rubygems.org'

gem 'awesome_print', '1.8'
gem 'bson', '~> 4.15'
gem 'correios-cep'
gem 'cucumber', '5.2'
gem 'dotenv', '2.7'
gem 'factory_bot'
gem 'faker', '2.17'
gem 'httparty', '0.18.1'
gem 'json'
gem 'json_matchers', '0.11.1'
gem 'mongo', '2.13.3'
gem 'pry', '0.12.2'
gem 'pry-nav'
gem 'pry-remote'
gem 'report_builder', '1.8'
gem 'rspec', '3.10'
gem 'rspec_junit_formatter', '~> 0.2.3'
gem 'solargraph'
